import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { url } from "inspector";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dashboards = [
  { texto: "Home", url: "/dashboard/home", icon: "home" },
  { texto: "Users", url: "/dashboard/user", icon: "users" },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
      </head>

      <body className="bg-gray-100">
        <header className="bg-white shadow">
          <nav className="container mx-auto flex items-center justify-between p-4">
            <a href="/" className="font-bold text-xl">
              Create Next App
            </a>
            <ul className="flex space-x-4">
              {dashboards.map((dashboard) => (
                <li key={dashboard.url}>
                  <a
                    href={dashboard.url}
                    className="flex items-center space-x-2">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-5 w-5"
                      viewBox="0 0 20 20"
                      fill="currentColor"
                      aria-hidden="true">
                      <path
                        fillRule="evenodd"
                        d="M10 3a1 1 0 00-.707.293l-6 6a1 1 0 000 1.414l6 6a1 1 0 001.414-1.414L5.414 10 10 5.414 14.586 10 10 14.586 8.293 12.879a1 1 0 00-1.414 1.414l6 6a1 1 0 001.414 0l6-6a1 1 0 000-1.414l-6-6A1 1 0 0010 3z"
                        clipRule="evenodd"
                      />
                    </svg>
                    <span>{dashboard.texto}</span>
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
